### ISSUE TITLE
구글스토어 게시

### ISSUE THREAD

**Issue by issac4892** [unsignd/deleteK#1]
https://developer.chrome.com/docs/webstore/publish/ 해줘요

**Comment by WieeRd** [comment]
어림도 없음

**Comment by unsignd** [comment]
> https://developer.chrome.com/docs/webstore/publish/ 해줘요 

올려주시겠다는 분들이 있긴한데
채널목록 업데이트땜에 일반 확장에 비해 업로드해주시는분 손이 많이가실거같기도 하고
이런거가지고 로고그리는것도 귀찮음ㅋㅋ;;
ㅈㅅㅈㅅ

**Comment by issac4892** [comment]
내가 ci만들어서온다 20년만기다려

**Comment by unsignd** [comment]
> 내가 ci만들어서온다 20년만기다려 

쩐다
